// Generated by tools/vp8_tables.py from libwebp v1.3.2. Do not edit: run the script.
//
// libwebp: Copyright 2010 Google Inc. All Rights Reserved. Used under the BSD-3-Clause
// license, https://github.com/webmproject/libwebp/blob/v1.3.2/COPYING
//
// src/dec/tree_dec.c sha256 ce07ffb41f06501b703df88e2a3775c70a52dd168f82621392c02eba01c1d27f
// src/dec/quant_dec.c sha256 5f21409c8f46d91474ed56ff671fab0a5ac60457f8abc8188f4025992dad80f5

package io.github.yuroyami.imagekodec.codec

/** The VP8 decoder's constant tables, as libwebp v1.3.2 holds them. */
internal object Vp8Tables {

    /** Default token probabilities, [type][band][context][node] (RFC 6386 section 13.5). `CoeffsProba0` in `src/dec/tree_dec.c`. */
    val COEFFS_PROBA_0: IntArray = unhex(
        "808080808080808080808080808080808080808080808080808080808080808080fd88feffe4db8080808080bd81f2ff" +
        "e3d5ffdb8080806a7ee3fcd6d1ffff8080800162f8ffece2ffff808080b585eefeddeaff9a8080804e86caf7c6b4ffdb" +
        "80808001b9f9fff3ff8080808080b896f7ffece080808080804d6ed8ffece680808080800165fbfff1ff8080808080aa" +
        "8bf1fcecd1ffff8080802574c4f3e4ffffff80808001ccfefff5ff8080808080cfa0faffee8080808080806667e7ffd3" +
        "ab80808080800198fcfff0ff8080808080b187f3ffeae180808080805081d3ffc2e080808080800101ff808080808080" +
        "8080f601ff8080808080808080ff80808080808080808080c623eddfc1bba2a0919b3e832dc6ddacb0dc9dfcdd01442f" +
        "92d095a7dda2ffdf800195f1ffdde0ffff808080b88deafddedcffc78080805163b5f2b0bef9caffff800181e8fdd6c5" +
        "f2c4ffff806379d2fac9c6ffca808080175ba3f2aabbf7d2ffff8001c8f6ffeaff80808080806db2f1ffe7f5ffff8080" +
        "802c82c9fdcdc0ffff8080800184effbdbd1ffa58080805e88e1fbdabeffff8080801664aef5baa1ffc780808001b6f9" +
        "ffe8eb80808080807c8ff1ffe3ea8080808080234db5fbc1d3ffcd808080019df7ffece7ffff808080798debffe1e3ff" +
        "ff8080802d63bcfbc3d9ffe08080800101fbffd5ff8080808080cb01f8ffff8080808080808901b1ffe0ff8080808080" +
        "fd09f8fbcfd0ffc0808080af0de0f3c1b9f9c6ffff804911abdda1b3eca7ffea80015ff7fdd4b7ffff808080ef5af4fa" +
        "d3d1ffff8080809b4dc3f8bcc3ffff8080800118effbdadbffcd808080c933dbffc4ba8080808080452ebeefc9daffe4" +
        "80808001bffbffff808080808080dfa5f9ffd5ff80808080808d7cf8ffff8080808080800110f8ffff808080808080be" +
        "24e6ffecff80808080809501ff808080808080808001e2ff8080808080808080f7c0ff8080808080808080f080ff8080" +
        "8080808080800186fcffff808080808080d53efaffff808080808080375dff8080808080808080808080808080808080" +
        "808080808080808080808080808080808080808080808080ca18d5ebbabfdca0f0afff7e26b6e8a9b8e4aeffbb803d2e" +
        "8adb97b2f0aaffd8800170e6fac7bff79fffff80a66de4fcd3d7ffae808080274da2e8acb4f5b2ffff800134dcf6c6c7" +
        "f9dcffff807c4abff3b7c1faddffff80184782db9aaaf3b6ffff8001b6e1f9dbf0ffe08080809596e2fcd8cdffab8080" +
        "801c6caaf2b7c2fedfffff800151e6fccccbffc08080807b66d1f7bcc4ffe9808080145f99f3a4adffcb80808001def8" +
        "ffd8d58080808080a8aff6fcebcdffff8080802f74d7ffd3d4ffff8080800179ecfdd4d6ffff8080808d54d5fcc9caff" +
        "db8080802a50a0f0a2b9ffcd8080800101ff8080808080808080f401ff8080808080808080ee01ff8080808080808080",
        bytesPerValue = 1,
    )

    /** CRC-32 of [COEFFS_PROBA_0] as libwebp holds it, 1 big-endian byte(s) a value. */
    const val COEFFS_PROBA_0_CRC32: Long = 0x71A910E9L

    /** Probabilities that a frame header updates a token probability, in the same layout (section 13.4). `CoeffsUpdateProba` in `src/dec/tree_dec.c`. */
    val COEFFS_UPDATE_PROBA: IntArray = unhex(
        "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffb0f6ffffffffffffffffffdff1fcff" +
        "fffffffffffffff9fdfdfffffffffffffffffff4fcffffffffffffffffeafefefffffffffffffffffdffffffffffffff" +
        "fffffffff6feffffffffffffffffeffdfefffffffffffffffffefffefffffffffffffffffff8fefffffffffffffffffb" +
        "fffefffffffffffffffffffffffffffffffffffffffffdfefffffffffffffffffbfefefffffffffffffffffefffeffff" +
        "fffffffffffffffefdfffefffffffffffffafffefffefffffffffffffeffffffffffffffffffffffffffffffffffffff" +
        "ffffffffffffffffffffffffffffffffffffffffffffffffd9ffffffffffffffffffffe1fcf1fdfffffeffffffffeafa" +
        "f1fafdfffdfefffffffffeffffffffffffffffffdffefeffffffffffffffffeefdfefefffffffffffffffff8feffffff" +
        "fffffffffff9fefffffffffffffffffffffffffffffffffffffffffffdfffffffffffffffffff7feffffffffffffffff" +
        "fffffffffffffffffffffffffffdfefffffffffffffffffcfffffffffffffffffffffffffffffffffffffffffffffefe" +
        "fffffffffffffffffdfffffffffffffffffffffffffffffffffffffffffffffefdfffffffffffffffffaffffffffffff" +
        "fffffffffeffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" +
        "bafbfaffffffffffffffffeafbf4fefffffffffffffffbfbf3fdfefffefffffffffffdfeffffffffffffffffecfdfeff" +
        "fffffffffffffffbfdfdfefefffffffffffffffefefffffffffffffffffefefeffffffffffffffffffffffffffffffff" +
        "fffffffffefffffffffffffffffffefefffffffffffffffffffefffffffffffffffffffffffffffffffffffffffffffe" +
        "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" +
        "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff" +
        "fffffffffffffffffffffffffffffffffffffffffffffffff8fffffffffffffffffffffafefcfefffffffffffffff8fe" +
        "f9fdfffffffffffffffffdfdfffffffffffffffff6fdfdfffffffffffffffffcfefbfefefffffffffffffffefcffffff" +
        "fffffffffff8fefdfffffffffffffffffdfffefefffffffffffffffffbfefffffffffffffffff5fbfeffffffffffffff" +
        "fffdfdfefffffffffffffffffffbfdfffffffffffffffffcfdfefffffffffffffffffffefffffffffffffffffffffcff" +
        "fffffffffffffffff9fffefffffffffffffffffffffefffffffffffffffffffffdfffffffffffffffffaffffffffffff" +
        "fffffffffffffffffffffffffffffffffffffffffffffffffffffeffffffffffffffffffffffffffffffffffffffffff",
        bytesPerValue = 1,
    )

    /** CRC-32 of [COEFFS_UPDATE_PROBA] as libwebp holds it, 1 big-endian byte(s) a value. */
    const val COEFFS_UPDATE_PROBA_CRC32: Long = 0xC531335AL

    /** 4x4 intra mode tree probabilities, [above mode][left mode][node] (section 11.5). `kBModesProba` in `src/dec/tree_dec.c`. */
    val BMODES_PROBA: IntArray = unhex(
        "e7783059737178987098b3407eaa762e465faf458f505552489b67383a0aabdabd110d98721a11a32cc3150aad791850" +
        "c31a3e2c405590470a26abd590221aaa2e371388a021ce473f14087272d00c09e251280b60b6541d102486b759896265" +
        "6aa59448bb64829d6f204b504266a7634a3e28ea80293509b2f18d1a086b4a2b1a9249a631179d412669a033341f7380" +
        "684f0c1bd9ff5711075744472c72330fba172f290e6eb6b71511c2422d1966c5bd171216585893962a2e2dc4cd2b61b7" +
        "75552623b33d2735c8571a152be8ab3822336872661d5d4d271c55ab3aa55a6240221674ce17222ba6496b36201a3301" +
        "512b1f44196a1640ab24e1722213156684bc104c7c3e124e5f5539323033c165239fd76f592e6f3c941facdbe415126f" +
        "70714d55b3ff267872282a01c4f5d10a196d582b1d8ca6d5252b9a3d3f1e9b432d4401d16450082b9a01331a478e4e4e" +
        "10ff8022c5ab29280566d3b70401dd333211a8d1c01719528a1f24ab1ba6262ce543573aa952731a3bb33f3b5ab43ba6" +
        "5d499a282815748fd12227af2f0f10b722df312db72e1121b706620f20b7392e16188001361125412049731c801780cd" +
        "2803097333c01206df572509733b4d40152f68372cda09363582e2405a46cd2829171a39363970b8052926a6d51e221a" +
        "8598740a2086271335dd1a722049ff1f0941ea020f0176494b200c33c0ffa02b33581f2343665537ba553815176f3bcd" +
        "2d25c03726467c49660122627d622a58685575af525f543559806471652d4b4f7b2f338051ab01391105476639352931" +
        "26210d7939491a0155290a438a4d6e5a2f727315020a66ffa61706651d100a558065c41a39120a6666d522142b75140f" +
        "24a38044011a663d472522351ff3c0453c472649771cde25442d8022012f0bf5ab3e1113469255373e46252b259a64a3" +
        "55a0013f095c881c4020c9554b0f090940ffb8771056061c0540ff19f8013808118489ff3774803a0f145287391a7928" +
        "a4321f899a851923da33672c83837b1f069e5628408794e02db780161a1183f09a0e01d12d10155b40de0701c5381527" +
        "9b3c8a1766d5530c0d36c0ff442f1c551a555580802092ab120b073f90ab0404f6231b0a92aeab0c1a80be502363b450" +
        "7e362d557e2f57b033291420654b808b769274805538290fb0ec5525093e471e117776ff11128a65263c8a37462b1a8e" +
        "9224131eabff611b148a2d3d3edb0151bc4020291475978e1415a370130c3dc380300418",
        bytesPerValue = 1,
    )

    /** CRC-32 of [BMODES_PROBA] as libwebp holds it, 1 big-endian byte(s) a value. */
    const val BMODES_PROBA_CRC32: Long = 0x55C10377L

    /** DC quantizer step for each quantizer index (section 14.1). `kDcTable` in `src/dec/quant_dec.c`. */
    val DC_TABLE: IntArray = unhex(
        "0405060708090a0a0b0c0d0e0f101111121314141515161617171819191a1b1c1d1e1f20212223242525262728292a2b" +
        "2c2d2e2e2f303132333435363738393a3b3c3d3e3f404142434445464748494a4b4c4c4d4e4f50515253545556575859" +
        "5b5d5f6062646566686a6c6e707274767a7c7e80828486888a8c8f9194979a9d",
        bytesPerValue = 1,
    )

    /** CRC-32 of [DC_TABLE] as libwebp holds it, 1 big-endian byte(s) a value. */
    const val DC_TABLE_CRC32: Long = 0xA7CCD2BFL

    /** AC quantizer step for each quantizer index (section 14.1). `kAcTable` in `src/dec/quant_dec.c`. */
    val AC_TABLE: IntArray = unhex(
        "000400050006000700080009000a000b000c000d000e000f0010001100120013001400150016001700180019001a001b" +
        "001c001d001e001f0020002100220023002400250026002700280029002a002b002c002d002e002f0030003100320033" +
        "003400350036003700380039003a003c003e00400042004400460048004a004c004e00500052005400560058005a005c" +
        "005e00600062006400660068006a006c006e0070007200740077007a007d0080008300860089008c008f009200950098" +
        "009b009e00a100a400a700aa00ad00b100b500b900bd00c100c500c900cd00d100d500d900dd00e100e500ea00ef00f5" +
        "00f900fe01030108010d01120117011c",
        bytesPerValue = 2,
    )

    /** CRC-32 of [AC_TABLE] as libwebp holds it, 2 big-endian byte(s) a value. */
    const val AC_TABLE_CRC32: Long = 0xDF17E658L

    private fun unhex(hex: String, bytesPerValue: Int): IntArray {
        val digits = 2 * bytesPerValue
        return IntArray(hex.length / digits) { hex.substring(it * digits, it * digits + digits).toInt(16) }
    }
}
