#!/usr/bin/env python3
"""
Writes Vp8Tables.kt, the constant tables of the VP8 (lossy WebP) decoder, from
libwebp's own source, so no table is typed by hand.

VP8 defines its default token probabilities, their update probabilities, the
4x4 intra mode probabilities and the quantizer steps as data (RFC 6386 sections
13.5, 13.4, 11.5 and 14.1). Nothing derives them, so they are copied, and this
script is the only way they enter the tree: it reads the arrays from a libwebp
checkout at the tag the oracle tests use, checks each one's shape, and writes
them with the SHA-256 of every file it read and the CRC-32 of every table.
Vp8TablesTest holds the Kotlin file to those CRCs, so an edit by hand fails.

    git clone --depth 1 --branch v1.3.2 https://github.com/webmproject/libwebp
    python3 tools/vp8_tables.py libwebp > \\
        imagekodec/src/commonMain/kotlin/io/github/yuroyami/imagekodec/codec/Vp8Tables.kt

libwebp is under the BSD-3-Clause license; the generated file keeps its notice.
"""
import hashlib
import re
import sys
import zlib

TAG = "v1.3.2"

# name in the Kotlin file, source file, C array name, expected element count, description
TABLES = [
    ("COEFFS_PROBA_0", "src/dec/tree_dec.c", "CoeffsProba0", 4 * 8 * 3 * 11,
     "Default token probabilities, [type][band][context][node] (RFC 6386 section 13.5)."),
    ("COEFFS_UPDATE_PROBA", "src/dec/tree_dec.c", "CoeffsUpdateProba", 4 * 8 * 3 * 11,
     "Probabilities that a frame header updates a token probability, in the same layout (section 13.4)."),
    ("BMODES_PROBA", "src/dec/tree_dec.c", "kBModesProba", 10 * 10 * 9,
     "4x4 intra mode tree probabilities, [above mode][left mode][node] (section 11.5)."),
    ("DC_TABLE", "src/dec/quant_dec.c", "kDcTable", 128,
     "DC quantizer step for each quantizer index (section 14.1)."),
    ("AC_TABLE", "src/dec/quant_dec.c", "kAcTable", 128,
     "AC quantizer step for each quantizer index (section 14.1)."),
]


def array_values(source, name):
    match = re.search(r"\b" + re.escape(name) + r"\s*(\[[^=]*\])?\s*=\s*\{", source)
    if not match:
        sys.exit(f"{name}: not found")
    depth = 0
    start = match.end() - 1
    for i in range(start, len(source)):
        if source[i] == "{":
            depth += 1
        elif source[i] == "}":
            depth -= 1
            if depth == 0:
                body = source[start:i + 1]
                break
    else:
        sys.exit(f"{name}: unterminated")
    body = re.sub(r"//[^\n]*|/\*.*?\*/", "", body, flags=re.S)
    return [int(v, 0) for v in re.findall(r"0x[0-9a-fA-F]+|\d+", body)]


def main():
    if len(sys.argv) != 2:
        sys.exit("usage: vp8_tables.py LIBWEBP_CHECKOUT")
    root = sys.argv[1].rstrip("/")
    files = {}
    for _, path, _, _, _ in TABLES:
        if path not in files:
            with open(f"{root}/{path}", "rb") as f:
                files[path] = f.read()
    out = []
    w = out.append
    w("// Generated by tools/vp8_tables.py from libwebp " + TAG + ". Do not edit: run the script.")
    w("//")
    w("// libwebp: Copyright 2010 Google Inc. All Rights Reserved. Used under the BSD-3-Clause")
    w("// license, https://github.com/webmproject/libwebp/blob/" + TAG + "/COPYING")
    w("//")
    for path, data in files.items():
        w(f"// {path} sha256 {hashlib.sha256(data).hexdigest()}")
    w("")
    w("package io.github.yuroyami.imagekodec.codec")
    w("")
    w("/** The VP8 decoder's constant tables, as libwebp " + TAG + " holds them. */")
    w("internal object Vp8Tables {")
    for kotlin, path, c_name, count, doc in TABLES:
        values = array_values(files[path].decode("utf-8"), c_name)
        if len(values) != count:
            sys.exit(f"{c_name}: {len(values)} values, expected {count}")
        if any(v < 0 or v > 0xFFFF for v in values):
            sys.exit(f"{c_name}: a value outside 0..65535")
        wide = any(v > 0xFF for v in values)
        data = b"".join(v.to_bytes(2 if wide else 1, "big") for v in values)
        hexed = data.hex()
        w("")
        w(f"    /** {doc} `{c_name}` in `{path}`. */")
        w(f"    val {kotlin}: IntArray = unhex(")
        for i in range(0, len(hexed), 96):
            w(f'        "{hexed[i:i + 96]}" +')
        out[-1] = out[-1][:-2] + ","
        w(f"        bytesPerValue = {2 if wide else 1},")
        w("    )")
        w("")
        w(f"    /** CRC-32 of [{kotlin}] as libwebp holds it, {2 if wide else 1} big-endian byte(s) a value. */")
        w(f"    const val {kotlin}_CRC32: Long = 0x{zlib.crc32(data):08X}L")
    w("")
    w("    private fun unhex(hex: String, bytesPerValue: Int): IntArray {")
    w("        val digits = 2 * bytesPerValue")
    w("        return IntArray(hex.length / digits) { hex.substring(it * digits, it * digits + digits).toInt(16) }")
    w("    }")
    w("}")
    print("\n".join(out))


if __name__ == "__main__":
    main()
